Bump com.google.devtools.ksp from 1.9.20-1.0.14 to 1.9.21-1.0.15 (#169)
Bumps [com.google.devtools.ksp](https://github.com/google/ksp) from
1.9.20-1.0.14 to 1.9.21-1.0.15.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/google/ksp/releases">com.google.devtools.ksp's
releases</a>.</em></p>
<blockquote>
<h2>1.9.21-1.0.15</h2>
<p>This is a hot fix to <a
href="https://redirect.github.com/google/ksp/issues/1591">#1591</a>
where multiple KMP projects were affected.</p>
<h3>Issues Fixed / PRs Merged</h3>
<p><a
href="https://redirect.github.com/google/ksp/issues/1591">#1591</a>
Error: Rewrite at slice LEXICAL_SCOPE key: ANNOTATION_ENTRY old value
<a href="https://redirect.github.com/google/ksp/issues/1612">#1612</a>
Filter out the <code>-progressive</code> compiler flag in KSP tasks
<a href="https://redirect.github.com/google/ksp/issues/1614">#1614</a>
Revert back to the non-thread-local KSP compiler plugin
implementation.</p>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/google/ksp/commit/5b0ae1823b3b82463b0a412bc507e4449e8b85d0"><code>5b0ae18</code></a>
UPDATE_KOTLIN_VERSION: 1.9.21</li>
<li><a
href="https://github.com/google/ksp/commit/3ada06de44ffba04e5252a9aff826a8fe8be9652"><code>3ada06d</code></a>
remove unused suppress annotation in KSP2</li>
<li><a
href="https://github.com/google/ksp/commit/e15fc17530390b91910f0372a6f81814ca0aa9c7"><code>e15fc17</code></a>
Turn off -progressive when downgrading from K2</li>
<li><a
href="https://github.com/google/ksp/commit/f5e489f747de23e3a67516020bc465b6ffdce1e8"><code>f5e489f</code></a>
Do not pick d44ad7d982 which is risky for 1.0.15</li>
<li><a
href="https://github.com/google/ksp/commit/85f9cac5b3f53eab368f19e3296430add0fadbcb"><code>85f9cac</code></a>
use non thread safe object cache for KSP1</li>
<li><a
href="https://github.com/google/ksp/commit/80447d5d7c2507bfda28d117b963b17465f35f07"><code>80447d5</code></a>
UPDATE AA VERSION: 2.0.0-dev-7674</li>
<li><a
href="https://github.com/google/ksp/commit/cdc65170bcf38fcd020f1a799fb6226710134023"><code>cdc6517</code></a>
Fix dependencies</li>
<li><a
href="https://github.com/google/ksp/commit/de324d61c2fd6ca04b06ed01760c3a533a9de4f1"><code>de324d6</code></a>
annotation call resolver: lookup scope before creating one</li>
<li><a
href="https://github.com/google/ksp/commit/fcf67b3ece49db4a9aab3bb52ebf66f5829d5ea0"><code>fcf67b3</code></a>
Update test expectations due to order changes.</li>
<li><a
href="https://github.com/google/ksp/commit/ea17eeaaa53a79272beeff3851bdf2c3e644fe13"><code>ea17eea</code></a>
UPDATE AA VERSION: 2.0.0-dev-6573</li>
<li>Additional commits viewable in <a
href="https://github.com/google/ksp/compare/1.9.20-1.0.14...1.9.21-1.0.15">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=com.google.devtools.ksp&package-manager=gradle&previous-version=1.9.20-1.0.14&new-version=1.9.21-1.0.15)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>